version: '3.8'

services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
    - app-network
    
  user-service:
    build:
      context: ./user_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    networks:
    - app-network

  company-service:
    build:
      context: ./company_service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    networks:
    - app-network
    
networks:
  app-network:
    driver: bridge
